### ISSUE TITLE
Just minor issue for a quick chat

### ISSUE THREAD

**Issue by LiteSoul** [Manwe-777/webrtc-example#1]
Hey there, I'm and Arg React dev too. I would like to chat with you on private, it's important, would that be possible?
One way could be through my ig https://www.instagram.com/arielblasi/ , or let me know the channel, thanks!
(no I'm not a bot/spam)

**Comment by Manwe-777** [comment]
Hi there ! Im usually active on Discord at Manwe#5766

**Comment by LiteSoul** [comment]
Thanks!
